version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://adac:adac@postgres:5432/adac
      - REDIS_URL=redis://redis:6379

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=adac
      - POSTGRES_PASSWORD=adac
      - POSTGRES_DB=adac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: