version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/adac
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=adac

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data: